---
{{- if .Values.ingress.enabled }}
{{- $fullname := (include "magalu-machine-learning-engineer-challenge.fullname" .) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullname }}-ingress
  namespace: {{ .Release.Namespace | quote }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        - path: {{ .path | quote }}
          pathType: Prefix
          backend:
            service:
              name: {{ $fullname }}-service
              port:
                number: 8000
    {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
{{ end }}
