nameOverride: ""
fullnameOverride: ""
loadBalancerClass: ""

service:
  enabled: true
  port: 8000

ingress:
  enabled: true
  annotations:
  hosts:
    - host: "customer-ml.192.168.49.2.nip.io"
      path: "/"

  tls:
    - secretName: "customer-tls"
      hosts:
        - "customer-ml.192.168.49.2.nip.io"

hpa:
  enabled: true

deployment:
  enabled: true
  image:
    repository: customer-ml
    tag: "latest"
    pullPolicy: Never
  serviceAccount:
    create: true
    name: ""
    annotations: {}
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  nodeSelector: {}
  tolerations: []
  priorityClassName: ""
  runtimeClassName: ""
  affinity: {}
  args: {}
  command: []
  livenessProbe:
    enabled: false
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  readinessProbe:
    enabled: false
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1

env: []
# - name: ""
#   value: ""
secret: []
# - envName: ""
#   secretName: ""
#   secretKey: ""
extraEnv: ~
# eg:
# extraEnv: |
#   - name: EXAMPLE
#     value: 'True'

ports:
  deployment: 8000
