name: Run Python tests

on:
  pull_request:

jobs:
  black:
    if: startsWith(github.head_ref, 'develop')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rickstaa/action-black@v1

  #  https://github.com/py-actions/flake8
  flake8:
    if: startsWith(github.head_ref, 'develop')
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: flake8 Lint
        uses: py-actions/flake8@v1
        with:
          max-line-length: 100

  # mypy:
  #   # or specify a path!
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: mypy check
  #       uses: jpetrucciani/mypy-check@master
  #       with:
  #         path: '.'

  tests:
    if: startsWith(github.head_ref, 'develop')
    runs-on: ubuntu-latest
    needs: [black, flake8]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install poetry
        run: |
          python -m pip install poetry

      - name: Configure poetry
        run: |
          python -m poetry config virtualenvs.in-project true

      - name: Cache the virtualenv
        uses: actions/cache@v2
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: |
          python -m poetry install --without dev

      - name: Run tests
        run: |
          python -m poetry run python -m pytest --cov=. -sxv

      - uses: stefanzweifel/git-auto-commit-action@v5
